tap "homebrew/cask"

brew "k9s"
brew "jq"
brew "kind"
brew "kubernetes-cli"
brew "docker-compose"
brew "lazygit"
brew "markdownlint-cli"
brew "node"
brew "neovim"
brew "stern"
brew "telnet"
brew "quarkus"
brew "google-java-format"
brew "bensadeh/circumflex/circumflex"

cask "brave-browser"
cask "firefox"
cask "font-jetbrains-mono-nerd-font"   
cask "rectangle"
cask "visual-studio-code"
cask "eurkey" 
cask "font-3270-nerd-font"
cask "iterm2"
cask "stats"
cask "amethyst"
