require("fwiedmann/packer")
require('fwiedmann/options')
require('fwiedmann/which-key')
require("fwiedmann/keybindings")


require('fwiedmann/autopairs')
require('fwiedmann/cmp')
require('fwiedmann/color')
require('fwiedmann/comment')
require('fwiedmann/git')
require('fwiedmann/nvim-tree')
require('fwiedmann/telescope')
require('fwiedmann/toggleterm')
require('fwiedmann/treesitter')
require('fwiedmann/ts-autotag')
require('fwiedmann/lualine')
require("fwiedmann/lsp")
require("fwiedmann.indentline")
require("fwiedmann.alpha")
require("fwiedmann/colorizer")
require("fwiedmann/bufferline")
require("fwiedmann/lspsaga")
require("fwiedmann/autocmd")
require("fwiedmann/dap")
require("fwiedmann/cloak")
require('fwiedmann/test')
require('fwiedmann/harpoon')
